/**
 * report-weekly.js â€” Generate weekly report by aggregating daily reports
 *
 * Queries the last 7 daily_reports entries and merges them into a weekly summary
 * with totals, averages, and trend data.
 *
 * Usage:
 *   v2 report weekly --db state.db --json
 *   v2 report weekly --db state.db --table
 *
 * Options:
 *   --db             Required. SQLite database path
 *   --end-date       End date of the week (default: today)
 *   --json           JSON output (default)
 *   --table          Table output
 *   --sample         Return sample report without DB interaction
 *   --help           Show this help text
 */

const { parseArgs, resolveDbPath, getOutputFormat } = require('../lib/cli');
const { printOutput, envelope, errorEnvelope } = require('../lib/output');
const { openStateDb, makeId } = require('../lib/state_db');
const { nowIso, localDateOnly, daysAgo, addDays } = require('../lib/dates');

const TOOL = 'report-weekly';

const HELP = `
report-weekly â€” Generate weekly report from daily reports

USAGE
  v2 report weekly --db <path> [options]

OPTIONS
  --db              SQLite database path (or CLIENT_DB_PATH env var)
  --end-date        End date for the weekly window (default: today, YYYY-MM-DD)
  --json            JSON output (default)
  --table           Table output
  --sample          Return sample report without DB interaction
  --help            Show this help text

EXAMPLES
  v2 report weekly --db state.db --json
  v2 report weekly --db state.db --end-date 2026-06-02
  v2 report weekly --db state.db --sample

REPORT CONTENTS
  Aggregates the last 7 daily reports into:
  â€¢ Weekly task totals (created, completed)
  â€¢ Event summary by type
  â€¢ GSC click/impression totals
  â€¢ SERP check counts
  â€¢ Infrastructure summary
  â€¢ Day-by-day breakdown

REQUIREMENTS
  Requires daily reports to have been generated (via report-daily).
  Missing days are skipped with a warning.
`.trim();

function generateWeeklyMarkdown(report) {
  const d = report;
  const lines = [
    `# {{SITE_NAME}} Weekly Report`,
    '',
    `Period: ${d.start_date} â€” ${d.end_date}`,
    `Generated: ${d.generated_at}`,
    `Days with reports: ${d.days_with_data} / 7`,
    '',
    '## Weekly Task Summary',
    '',
    `- Tasks created this week: ${d.totals.tasks_created}`,
    `- Tasks completed this week: ${d.totals.tasks_completed}`,
    `- Current task total: ${d.totals.current_total_tasks}`,
    '',
    '## Weekly Event Summary',
    '',
    `- Total events: ${d.totals.total_events}`,
  ];

  if (d.totals.events_by_type && Object.keys(d.totals.events_by_type).length > 0) {
    for (const [type, count] of Object.entries(d.totals.events_by_type)) {
      lines.push(`  - ${type}: ${count}`);
    }
  }

  lines.push('');
  lines.push('## GSC Weekly');
  lines.push('');
  lines.push(`- Total clicks: ${d.totals.gsc_clicks}`);
  lines.push(`- Total impressions: ${d.totals.gsc_impressions}`);
  lines.push('');

  lines.push('## SERP Weekly');
  lines.push('');
  lines.push(`- Total checks: ${d.totals.serp_checks}`);
  lines.push('');

  lines.push('## Day-by-Day Breakdown');
  lines.push('');
  lines.push('| Date | Tasks Created | Completed | Events | GSC Clicks | SERP Checks |');
  lines.push('| --- | --- | --- | --- | --- | --- |');

  for (const day of d.daily_breakdown) {
    lines.push(`| ${day.date} | ${day.tasks_created} | ${day.tasks_completed} | ${day.events} | ${day.gsc_clicks} | ${day.serp_checks} |`);
  }

  lines.push('');
  lines.push('---');
  lines.push('*Generated by {{SITE_NAME}} Agent*');

  return lines.join('\n');
}

module.exports = function reportWeekly() {
  const args = parseArgs();

  if (args.help) {
    console.log(HELP);
    return;
  }

  if (args.sample) {
    const today = localDateOnly();
    const weekAgo = daysAgo(7);
    printOutput(envelope({
      start_date: weekAgo,
      end_date: today,
      days_with_data: 5,
      totals: {
        tasks_created: 18,
        tasks_completed: 12,
        current_total_tasks: 45,
        total_events: 156,
        events_by_type: { task_status_changed: 60, lock_acquired: 30, lock_released: 30, task_candidate_created: 36 },
        gsc_clicks: 840,
        gsc_impressions: 24500,
        serp_checks: 105,
      },
      daily_breakdown: [
        { date: daysAgo(6), tasks_created: 3, tasks_completed: 2, events: 22, gsc_clicks: 120, serp_checks: 15 },
        { date: daysAgo(5), tasks_created: 4, tasks_completed: 3, events: 28, gsc_clicks: 130, serp_checks: 15 },
        { date: daysAgo(4), tasks_created: 2, tasks_completed: 1, events: 18, gsc_clicks: 110, serp_checks: 15 },
        { date: daysAgo(3), tasks_created: 5, tasks_completed: 3, events: 35, gsc_clicks: 140, serp_checks: 15 },
        { date: daysAgo(2), tasks_created: 4, tasks_completed: 3, events: 53, gsc_clicks: 340, serp_checks: 45 },
      ],
    }, { tool: TOOL }), getOutputFormat(args));
    return;
  }

  try {
    const dbPath = resolveDbPath(args);
    const db = openStateDb(dbPath);

    try {
      const now = nowIso();
      const endDate = args['end-date'] || localDateOnly();
      // Anchor the 7-day window to endDate so historical reports work. Using
      // daysAgo(7) here would hardcode "7 days before today", producing an
      // empty window whenever --end-date is in the past.
      const startDate = addDays(endDate, -6);

      // Fetch daily reports for the week
      const dailyReports = db.prepare(`
        SELECT report_date, report_json
        FROM daily_reports
        WHERE report_date >= ? AND report_date <= ?
        ORDER BY report_date ASC
      `).all(startDate, endDate);

      // Aggregate
      let totalTasksCreated = 0;
      let totalTasksCompleted = 0;
      let totalEvents = 0;
      let totalGscClicks = 0;
      let totalGscImpressions = 0;
      let totalSerpChecks = 0;
      const allEventsByType = {};
      const dailyBreakdown = [];
      let currentTotalTasks = 0;

      for (const dr of dailyReports) {
        let data;
        try {
          data = JSON.parse(dr.report_json);
        } catch {
          continue;
        }

        const dayCreated = data.tasks?.created_today || 0;
        const dayCompleted = data.tasks?.completed_today || 0;
        const dayEvents = data.events?.total_today || 0;
        const dayClicks = data.gsc?.total_clicks || 0;
        const dayImpressions = data.gsc?.total_impressions || 0;
        const daySerp = data.serp?.checks_today || 0;

        totalTasksCreated += dayCreated;
        totalTasksCompleted += dayCompleted;
        totalEvents += dayEvents;
        totalGscClicks += dayClicks;
        totalGscImpressions += dayImpressions;
        totalSerpChecks += daySerp;
        currentTotalTasks = data.tasks?.total || currentTotalTasks;

        if (data.events?.by_type) {
          for (const [type, count] of Object.entries(data.events.by_type)) {
            allEventsByType[type] = (allEventsByType[type] || 0) + count;
          }
        }

        dailyBreakdown.push({
          date: dr.report_date,
          tasks_created: dayCreated,
          tasks_completed: dayCompleted,
          events: dayEvents,
          gsc_clicks: dayClicks,
          gsc_impressions: dayImpressions,
          serp_checks: daySerp,
        });
      }

      const report = {
        start_date: startDate,
        end_date: endDate,
        generated_at: now,
        days_with_data: dailyReports.length,
        totals: {
          tasks_created: totalTasksCreated,
          tasks_completed: totalTasksCompleted,
          current_total_tasks: currentTotalTasks,
          total_events: totalEvents,
          events_by_type: allEventsByType,
          gsc_clicks: totalGscClicks,
          gsc_impressions: totalGscImpressions,
          serp_checks: totalSerpChecks,
        },
        daily_breakdown: dailyBreakdown,
      };

      const markdown = generateWeeklyMarkdown(report);

      if (dailyReports.length === 0) {
        report.warning = `No daily reports found for ${startDate} â€” ${endDate}. Run report-daily first.`;
      }

      printOutput(envelope({
        ...report,
        markdown,
      }, { tool: TOOL }), getOutputFormat(args));

    } finally {
      db.close();
    }

  } catch (err) {
    printOutput(errorEnvelope(err, { tool: TOOL }), 'json');
    process.exitCode = 1;
  }
};

if (require.main === module) {
  module.exports();
}