/**
 * report-daily.js â€” Generate daily report
 *
 * Queries task stats, recent events, GSC/SERP data from the DB and produces
 * a comprehensive daily summary. Stores result in the daily_reports table.
 *
 * Usage:
 *   v2 report daily --db state.db --json
 *   v2 report daily --db state.db --date 2026-06-02
 *
 * Options:
 *   --db             Required. SQLite database path
 *   --date           Report date (default: today, YYYY-MM-DD format)
 *   --json           JSON output (default)
 *   --table          Table output
 *   --sample         Return sample report without DB interaction
 *   --help           Show this help text
 */

const { parseArgs, resolveDbPath, getOutputFormat } = require('../lib/cli');
const { printOutput, envelope, errorEnvelope } = require('../lib/output');
const { openStateDb, makeId } = require('../lib/state_db');
const { nowIso, localDateOnly } = require('../lib/dates');

const TOOL = 'report-daily';

const HELP = `
report-daily â€” Generate daily activity report

USAGE
  v2 report daily --db <path> [options]

OPTIONS
  --db              SQLite database path (or CLIENT_DB_PATH env var)
  --date            Report date in YYYY-MM-DD format (default: today)
  --json            JSON output (default)
  --table           Table output
  --sample          Return sample report without DB interaction
  --help            Show this help text

EXAMPLES
  v2 report daily --db state.db --json
  v2 report daily --db state.db --date 2026-06-02
  v2 report daily --db state.db --sample

REPORT CONTENTS
  â€¢ Task statistics (by status, created, completed)
  â€¢ Recent events summary
  â€¢ GSC data snapshot (clicks, impressions, top queries)
  â€¢ SERP check results
  â€¢ Lock activity
  â€¢ Deployment activity
  â€¢ Alert summary

The report is stored in the daily_reports table for historical tracking.
`.trim();

function generateMarkdown(report) {
  const d = report;
  const lines = [
    `# {{SITE_NAME}} Daily Report â€” ${d.report_date}`,
    '',
    `Generated: ${d.generated_at}`,
    '',
    '## Task Summary',
    '',
    `| Status | Count |`,
    `| --- | --- |`,
  ];

  for (const [status, count] of Object.entries(d.tasks.by_status || {})) {
    lines.push(`| ${status} | ${count} |`);
  }
  lines.push(`| **Total** | **${d.tasks.total}** |`);
  lines.push('');
  lines.push(`- Created today: ${d.tasks.created_today}`);
  lines.push(`- Completed today: ${d.tasks.completed_today}`);
  lines.push('');

  lines.push('## Events');
  lines.push('');
  lines.push(`- Total events today: ${d.events.total_today}`);
  if (d.events.by_type && Object.keys(d.events.by_type).length > 0) {
    lines.push('');
    for (const [type, count] of Object.entries(d.events.by_type)) {
      lines.push(`  - ${type}: ${count}`);
    }
  }
  lines.push('');

  if (d.gsc) {
    lines.push('## GSC Data');
    lines.push('');
    lines.push(`- Snapshots captured: ${d.gsc.snapshots_count}`);
    lines.push(`- Total clicks: ${d.gsc.total_clicks}`);
    lines.push(`- Total impressions: ${d.gsc.total_impressions}`);
    lines.push('');
  }

  if (d.serp) {
    lines.push('## SERP Checks');
    lines.push('');
    lines.push(`- Checks today: ${d.serp.checks_today}`);
    lines.push('');
  }

  lines.push('## Infrastructure');
  lines.push('');
  lines.push(`- Active locks: ${d.infrastructure.active_locks}`);
  lines.push(`- Deployments today: ${d.infrastructure.deployments_today}`);
  lines.push(`- Open alerts: ${d.infrastructure.open_alerts}`);
  lines.push(`- Pending outbox jobs: ${d.infrastructure.pending_outbox}`);
  lines.push('');
  lines.push('---');
  lines.push('*Generated by {{SITE_NAME}} Agent*');

  return lines.join('\n');
}

module.exports = function reportDaily() {
  const args = parseArgs();

  if (args.help) {
    console.log(HELP);
    return;
  }

  if (args.sample) {
    const today = localDateOnly();
    const sampleReport = {
      report_date: today,
      tasks: {
        total: 45,
        by_status: { candidate: 10, approved: 5, in_progress: 3, completed: 25, failed: 2 },
        created_today: 4,
        completed_today: 3,
      },
      events: { total_today: 28, by_type: { task_status_changed: 12, lock_acquired: 5, lock_released: 5, task_candidate_created: 6 } },
      gsc: { snapshots_count: 50, total_clicks: 120, total_impressions: 3500 },
      serp: { checks_today: 15 },
      infrastructure: { active_locks: 2, deployments_today: 1, open_alerts: 0, pending_outbox: 3 },
    };
    printOutput(envelope({
      report_date: today,
      report: sampleReport,
      markdown: generateMarkdown({ ...sampleReport, generated_at: nowIso() }),
    }, { tool: TOOL }), getOutputFormat(args));
    return;
  }

  try {
    const dbPath = resolveDbPath(args);
    const db = openStateDb(dbPath);

    try {
      const reportDate = args.date || localDateOnly();
      const now = nowIso();

      // Date boundaries for today's data
      const dayStart = `${reportDate}T00:00:00.000Z`;
      const dayEnd = `${reportDate}T23:59:59.999Z`;

      // --- TASKS ---
      const totalTasks = db.prepare('SELECT COUNT(*) as cnt FROM tasks').get().cnt;
      const tasksByStatus = db.prepare(
        'SELECT status, COUNT(*) as cnt FROM tasks GROUP BY status ORDER BY cnt DESC'
      ).all();
      const byStatus = {};
      for (const row of tasksByStatus) byStatus[row.status] = row.cnt;

      const createdToday = db.prepare(
        'SELECT COUNT(*) as cnt FROM tasks WHERE created_at >= ? AND created_at <= ?'
      ).get(dayStart, dayEnd).cnt;

      const completedToday = db.prepare(
        'SELECT COUNT(*) as cnt FROM tasks WHERE completed_at >= ? AND completed_at <= ?'
      ).get(dayStart, dayEnd).cnt;

      // --- EVENTS ---
      const eventsToday = db.prepare(
        'SELECT COUNT(*) as cnt FROM events WHERE created_at >= ? AND created_at <= ?'
      ).get(dayStart, dayEnd).cnt;

      const eventsByType = db.prepare(
        'SELECT event_type, COUNT(*) as cnt FROM events WHERE created_at >= ? AND created_at <= ? GROUP BY event_type ORDER BY cnt DESC'
      ).all(dayStart, dayEnd);
      const byType = {};
      for (const row of eventsByType) byType[row.event_type] = row.cnt;

      // --- GSC ---
      const gscSnapshots = db.prepare(
        'SELECT COUNT(*) as cnt, COALESCE(SUM(clicks), 0) as clicks, COALESCE(SUM(impressions), 0) as impressions FROM gsc_snapshots WHERE captured_at >= ? AND captured_at <= ?'
      ).get(dayStart, dayEnd);

      // --- SERP ---
      const serpChecks = db.prepare(
        'SELECT COUNT(*) as cnt FROM serp_checks WHERE created_at >= ? AND created_at <= ?'
      ).get(dayStart, dayEnd).cnt;

      // --- INFRASTRUCTURE ---
      const activeLocks = db.prepare("SELECT COUNT(*) as cnt FROM locks WHERE status = 'active'").get().cnt;
      const deploymentsToday = db.prepare(
        'SELECT COUNT(*) as cnt FROM deployments WHERE started_at >= ? AND started_at <= ?'
      ).get(dayStart, dayEnd).cnt;
      const openAlerts = db.prepare("SELECT COUNT(*) as cnt FROM monitor_alerts WHERE status = 'open'").get().cnt;
      const pendingOutbox = db.prepare("SELECT COUNT(*) as cnt FROM outbox_jobs WHERE status = 'pending'").get().cnt;

      // Build report
      const report = {
        report_date: reportDate,
        generated_at: now,
        tasks: {
          total: totalTasks,
          by_status: byStatus,
          created_today: createdToday,
          completed_today: completedToday,
        },
        events: { total_today: eventsToday, by_type: byType },
        gsc: {
          snapshots_count: gscSnapshots.cnt,
          total_clicks: gscSnapshots.clicks,
          total_impressions: gscSnapshots.impressions,
        },
        serp: { checks_today: serpChecks },
        infrastructure: {
          active_locks: activeLocks,
          deployments_today: deploymentsToday,
          open_alerts: openAlerts,
          pending_outbox: pendingOutbox,
        },
      };

      const markdown = generateMarkdown(report);

      // Store in daily_reports table
      const reportId = makeId('RPT');
      db.prepare(`
        INSERT OR REPLACE INTO daily_reports (report_id, report_date, report_json, report_markdown, status, created_at)
        VALUES (?, ?, ?, ?, 'generated', ?)
      `).run(reportId, reportDate, JSON.stringify(report), markdown, now);

      printOutput(envelope({
        report_id: reportId,
        report_date: reportDate,
        report,
        markdown,
      }, { tool: TOOL }), getOutputFormat(args));

    } finally {
      db.close();
    }

  } catch (err) {
    printOutput(errorEnvelope(err, { tool: TOOL }), 'json');
    process.exitCode = 1;
  }
};

if (require.main === module) {
  module.exports();
}