<#
.SYNOPSIS
  Generate scaffold-blog.ps1 configuration from the website profile.

.DESCRIPTION
  Reads website-profile.json (from analyze-website.ps1) and site.config.json,
  then outputs a scaffold configuration that tells scaffold-blog.ps1:
    - Which source post to clone header/footer from
    - What Analytics/Clarity IDs to embed
    - What social handles to use in schema
    - What favicon paths to reference
    - What CSS files to link

  Output is a JSON file (scaffold-config.json) and a human-readable summary.

.PARAMETER ProfilePath
  Path to website-profile.json. Default: ../website-profile.json

.PARAMETER ConfigPath
  Path to site.config.json. Default: ../site.config.json

.PARAMETER OutputPath
  Where to write scaffold-config.json. Default: ../Agentic SEO/tools/scaffold-config.json

.EXAMPLE
  pwsh ./setup/generate-scaffold-config.ps1
#>

[CmdletBinding()]
param(
    [string]$ProfilePath,
    [string]$ConfigPath,
    [string]$OutputPath
)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot

if (-not $ProfilePath) { $ProfilePath = Join-Path $repoRoot 'website-profile.json' }
if (-not $ConfigPath)  { $ConfigPath  = Join-Path $repoRoot 'site.config.json' }
if (-not $OutputPath)  { $OutputPath  = Join-Path $repoRoot 'Agentic SEO/tools/scaffold-config.json' }

if (-not (Test-Path $ProfilePath)) {
    throw "website-profile.json not found. Run analyze-website.ps1 first."
}
if (-not (Test-Path $ConfigPath)) {
    throw "site.config.json not found: $ConfigPath"
}

$wp  = Get-Content -Raw -Path $ProfilePath | ConvertFrom-Json
$cfg = Get-Content -Raw -Path $ConfigPath  | ConvertFrom-Json
$utf8 = New-Object System.Text.UTF8Encoding($false)

Write-Host ""
Write-Host "=== generate-scaffold-config ===" -ForegroundColor Cyan
Write-Host ""

# ============================================================
# BUILD THE CONFIG
# ============================================================
$scaffoldConfig = @{
    _comment        = "Generated by generate-scaffold-config.ps1 from website-profile.json. Used by scaffold-blog.ps1 and the production skill files."
    generated_at    = (Get-Date).ToString('yyyy-MM-ddTHH:mm:ssZ')

    # Identity
    domain          = $cfg.domain
    site_name       = $cfg.site_name
    niche           = $cfg.business.niche
    audience        = $cfg.business.audience

    # Source posts (best candidates for cloning header/footer)
    blog_source_post    = if ($wp.scaffold.best_source_post) { $wp.scaffold.best_source_post } else { "(none detected - add manually)" }
    service_source_post = if ($wp.scaffold.best_service_source) { $wp.scaffold.best_service_source } else { "(none detected - add manually)" }

    # Analytics
    analytics = @{
        ga4_id      = if ($wp.analytics.ga4_id) { $wp.analytics.ga4_id } else { "(not detected)" }
        gtm_id      = if ($wp.analytics.gtm_id) { $wp.analytics.gtm_id } else { "(not detected)" }
        clarity_id  = if ($wp.analytics.clarity_id) { $wp.analytics.clarity_id } else { "(not detected)" }
    }

    # Social handles (for schema sameAs array)
    social = @{
        twitter   = if ($wp.social.twitter_handle) { $wp.social.twitter_handle } else { "@TODO" }
        facebook  = if ($wp.social.facebook)  { "https://www.facebook.com/$($wp.social.facebook)/" } else { $null }
        youtube   = if ($wp.social.youtube)   { "https://www.youtube.com/@$($wp.social.youtube)" } else { $null }
        instagram = if ($wp.social.instagram) { "https://www.instagram.com/$($wp.social.instagram)/" } else { $null }
        linkedin  = if ($wp.social.linkedin)  { "https://www.linkedin.com/company/$($wp.social.linkedin)" } else { $null }
        pinterest = if ($wp.social.pinterest) { "https://www.pinterest.com/$($wp.social.pinterest)/" } else { $null }
        tiktok    = if ($wp.social.tiktok)    { "https://www.tiktok.com/@$($wp.social.tiktok)" } else { $null }
    }

    # Favicon paths
    favicon = @{
        ico             = if ($wp.favicon.ico) { $wp.favicon.ico } else { "/assets/favicon.ico" }
        apple_touch     = if ($wp.favicon.apple_touch_icon) { $wp.favicon.apple_touch_icon } else { "/assets/apple-touch-icon.webp" }
        webmanifest     = if ($wp.favicon.webmanifest) { $wp.favicon.webmanifest } else { "/assets/site.webmanifest" }
        variants        = if ($wp.favicon.variants) { $wp.favicon.variants } else { @() }
    }

    # CSS files the blog posts should link
    css_files = @("../css/main.css", "../css/blog.css")

    # JS files to include
    js_files = if ($wp.structure.js_files) { $wp.structure.js_files } else { @() }

    # Blog structure
    blog = @{
        directory       = if ($wp.blog.directory) { $wp.blog.directory } else { "/blog" }
        post_count      = if ($wp.blog.post_count) { $wp.blog.post_count } else { 0 }
        card_classes    = if ($wp.blog.card_classes) { $wp.blog.card_classes } else { @("blog-card reveal") }
        html_patterns   = if ($wp.blog.html_patterns) { $wp.blog.html_patterns } else { @{} }
    }

    # Brand palette
    brand_palette = @{
        navy_bg       = "#0F2A44"
        primary_accent = "#176B9A"
        alert_red     = "#E94743"
        success_green = "#74C9A7"
        highlight     = "#F4D77A"
        text_light    = "#FAFAF7"
    }

    # Existing blog posts (for link-registry seeding and related posts)
    existing_posts = if ($wp.blog.posts) { $wp.blog.posts } else { @() }

    # Existing service pages
    existing_services = if ($wp.services.pages) { $wp.services.pages } else { @() }
}

# Try to detect brand palette from extracted CSS variables
if ($wp.brand -and $wp.brand.css_variables) {
    $vars = $wp.brand.css_variables
    # Common variable name patterns for brand colors
    $navyPatterns   = @('navy', 'dark', 'primary-dark', 'bg-dark')
    $accentPatterns = @('accent', 'primary', 'brand', 'teal', 'blue')
    $redPatterns    = @('danger', 'error', 'alert', 'red')
    $greenPatterns  = @('success', 'green', 'positive')
    $yellowPatterns = @('warning', 'highlight', 'yellow', 'gold')

    foreach ($key in $vars.PSObject.Properties.Name) {
        $val = $vars.$key
        $lk = $key.ToLower()
        foreach ($p in $navyPatterns)   { if ($lk -match $p) { $scaffoldConfig.brand_palette.navy_bg = $val; break } }
        foreach ($p in $accentPatterns) { if ($lk -match $p) { $scaffoldConfig.brand_palette.primary_accent = $val; break } }
        foreach ($p in $redPatterns)    { if ($lk -match $p) { $scaffoldConfig.brand_palette.alert_red = $val; break } }
        foreach ($p in $greenPatterns)  { if ($lk -match $p) { $scaffoldConfig.brand_palette.success_green = $val; break } }
        foreach ($p in $yellowPatterns) { if ($lk -match $p) { $scaffoldConfig.brand_palette.highlight = $val; break } }
    }
}

# Remove null social entries
$cleanSocial = @{}
foreach ($key in $scaffoldConfig.social.Keys) {
    if ($scaffoldConfig.social[$key]) { $cleanSocial[$key] = $scaffoldConfig.social[$key] }
}
$scaffoldConfig.social = $cleanSocial

# ============================================================
# OUTPUT
# ============================================================
$json = $scaffoldConfig | ConvertTo-Json -Depth 10
[System.IO.File]::WriteAllText($OutputPath, $json, $utf8)

Write-Host "  Generated: $OutputPath" -ForegroundColor Green
Write-Host ""
Write-Host "  --- Summary ---" -ForegroundColor White
Write-Host "  Domain:            $($scaffoldConfig.domain)" -ForegroundColor Gray
Write-Host "  Site Name:         $($scaffoldConfig.site_name)" -ForegroundColor Gray
Write-Host "  Blog Source Post:  $($scaffoldConfig.blog_source_post)" -ForegroundColor Gray
Write-Host "  Service Source:    $($scaffoldConfig.service_source_post)" -ForegroundColor Gray
Write-Host "  GA4:               $($scaffoldConfig.analytics.ga4_id)" -ForegroundColor Gray
Write-Host "  Clarity:           $($scaffoldConfig.analytics.clarity_id)" -ForegroundColor Gray
Write-Host "  Twitter:           $($scaffoldConfig.social.twitter)" -ForegroundColor Gray
Write-Host "  Existing posts:    $($scaffoldConfig.existing_posts.Count)" -ForegroundColor Gray
Write-Host "  Existing services: $($scaffoldConfig.existing_services.Count)" -ForegroundColor Gray
Write-Host ""
Write-Host "  This config can be referenced by scaffold-blog.ps1 and the AI agent" -ForegroundColor Yellow
Write-Host "  when producing new blog posts or service pages." -ForegroundColor Yellow
Write-Host ""
